### ISSUE TITLE
Publish 0.0.6 to nats-jwt on npm

### ISSUE THREAD

**Issue by jonaskello** [nats-io/jwt.js#29]
### What motivated this proposal?

As far as I understand this repo is published to the npm package [nats-jwt](https://www.npmjs.com/package/nats-jwt?activeTab=versions). However the latest version on npm seems to be `0.0.5` while in this repo under releases there is `0.0.6`.

The new version has some changes that enables easier building of auth-callouts so it would nice to have them published.

### What is the proposed change?

Publish 0.0.6 to npm

### Who benefits from this change?

All users of this package

**Comment by aricart** [comment]
CI will release 0.0.7
